### ISSUE TITLE
Install Command installed old version

### ISSUE THREAD

**Issue by fawadasaurus** [apexlang/apex#11]
**Describe the bug**

I ran `deno install -A --unstable -f -n apex https://deno.land/x/apex_cli/apex.ts`.  I then tried to run `apex new` and I did not have the `-p` or the `-b` options available.

Running `apex upgrade` fixed the issue.  But this should not be needed if I am doing a fresh install.

**Actual behavior**

An `old`? version of apex was installed.

**Expected behavior**

The latest version of Apex is installed.

**To Reproduce**

`deno install -A --unstable -f -n apex https://deno.land/x/apex_cli/apex.ts` 

`apex`

**Environment (where applicable):**

- OS: OSX
- Architecture: Apple Silicon M1
- Build Version: 0.0.10

**Additional context** Add any other context about the problem here.

**Comment by jsoverson** [comment]
This is fixed with the install command on apexlang.io and the REAMDE now pointing directly to the latest version
